name: quem
version: '0.0.0'
main: net.azisaba.quem.Quem
bootstrapper: net.azisaba.quem.QuemBootstrap
api-version: '1.21'
dependencies:
  server:
    kunectron:
      load: AFTER
permissions:
  quem.debug:
    default: op
  quem.grant:
    default: op
  quem.progress:
    default: op
  quem.reload:
    default: op
  quem.revoke:
    default: op
  quem.stage:
    default: op